#!/bin/bash
remove_zeros() {
for original_name in `ls`; do
    # determine new file name from original:
    # remove zeroes and change extension.
    new_name=$(echo "$original_name" | sed -e 's/\.0*/\./g' -e s'/^0*//g' -e s'/-0*/-/g' )
    mv "$original_name" "$new_name"
done
}
#tcpflow -o $num-streams -r $PCAP
tcpflow -o 7-streams -r cap-7.pcapng
#cd $num-streams 
cd 7-streams 
remove_zeros
#FILES=`ls | grep "^$ip"`
#ls | grep "^192.168.15.7" | xargs rm
myip=`ifconfig | grep -A1 eth1 | grep inet | awk '{print $2}'`
ls | grep -v $myip  | xargs rm
ls | grep -v "^192.168.15.7" | xargs rm
FILES=`ls | grep "^192.168.15.7"`
for file in $FILES; do
	HEX=`xxd -p $file | tr -d '\n' | sed -e 's/.\{2\}/\\\\x&/g' -e s'/^/"/g' -e s'/$/"/g'`
	PORT=`echo $file | awk -F. '{print $5}' | cut -d- -f1`
	#echo $PORT $HEX >> portspoof-$ip.conf
	echo $PORT $HEX >> tmp.conf
done
sort -u < tmp.conf > portspoof-7.conf
rm tmp.conf
